add `MP_SMALL_STACK_SIZE` option
libtom/libtommath pull request #538
Opened 2022-10-27 15:03 UTC by sjaeckel

This adds an option to use a heap-buffer for the usually stack-based
`MP_WARRAY`-sized temporary buffers.

Per default it will reserve a single buffer, which can be modified
* at compile-time via the `MP_WARRAY_NUM` define
* at run-time by calling `mp_warray_init()`

The internal structure can only be created once. If one wants to modify
the maximum number of elements, the entire structure has to be free'd
by calling `mp_warray_free()`.

In case one wants to use this option with multiple threads, one shall
use the `mp_warray_init()` function and pass appropriate locking functions.

This fixes #441 #447 #511

2022-11-12 14:58 UTC, sjaeckel commented
@jlaitine could you maybe have a look and tell me whether that's an acceptable solution for you?

2023-03-31 16:54 UTC, czurnieden requested changes
Found nothing except some typos.

But the effect on the ECC computations *is* interesting!

2023-03-31 16:54 UTC, czurnieden commented on doc/bn.tex
> +is enabeled and multiple threads are used, c.f. \ref{ch:SMALL_STACK_INTRO} resp. \ref{ch:SMALL_STACK_API}
s/enabeled/enabled/

2023-03-31 16:54 UTC, czurnieden commented on doc/bn.tex
> +
Maybe add a sentence about the flag `preallocate`? It is clear in the code but a bit ambiguous here.

2023-06-21 13:02 UTC, czurnieden commented
What happened to this PR? Did you change your mind? I find it quite interesting to have a choice between stack and heap for this. On the other side: it breaks our general thread-safety and needs locks.
But I'm still supportive.

2024-03-11 14:25 UTC, sjaeckel commented on s_mp_warray_get.c
> +   ret = MP_CALLOC(MP_WARRAY, sizeof(mp_word));
I guess we have to live with the worst-case assumption as the default value.

2024-03-11 14:46 UTC, sjaeckel commented on .github/workflows/main.yml
> +        cc: [ clang-10, gcc ]
I can't really remember, but maybe it had to do with the CI runners at the time of the original PR still being 18.04 and 20.04, where 18.04 default clang was too old or something like that.

Fixed.

2024-03-11 15:09 UTC, sjaeckel commented
> What happened to this PR? Did you change your mind?

No, I just didn't have the passion to follow up :)

> On the other side: it breaks our general thread-safety and needs locks.

That's indeed a thing. I'm not sure whether it'd make sense to replace the locks by taking care of that ourselves and using lock-free/atomic operations under the hood!?

2024-03-14 15:03 UTC, sjaeckel commented
> I'm not sure whether it'd make sense to replace the locks by taking care of that ourselves and using lock-free/atomic operations under the hood!?

What do you think? Better like that!?

2024-03-15 01:38 UTC, czurnieden approved these changes

2024-03-15 01:52 UTC, czurnieden commented
Sorry, took a bit longer to check.

> Better like that!?

Yes, looks reasonable.

Caveat: I cannot test the Windows stuff now: my last PC here with Windows (what is the plural of Windows?) let the magic smoke out, need a visit to Ebay before going on.

PS: I am aware of my TODO list, it's not forgotten!

2024-03-15 08:24 UTC, sjaeckel commented
> what is the plural of Windows?

My SO just explained to me that the plural only works with the complete name! Microsoft Windows -> Microsoft**s** Windows

> my TODO list

No need to hurry, we have time.

> test the Windows stuff

I'll see what I can do by extending CI.

2024-03-15 23:05 UTC, czurnieden commented
> My SO just explained to me that the plural only works with the complete name! Microsoft Windows -> Microsofts Windows

Ah, ok, my thanks to your SO!

> I'll see what I can do by extending CI.

That would be really nice!

> No need to hurry, we have time.

You have, but I'm an overweight old fart already! ;-)

My main problem is the error I got with the base2->base10 conversion with a single round of NR to compute the next divisor at a very large (close to `MP_MAX_DIGIT_COUNT` with `MP_64BIT` ) number. Sadly a randomly generated large number and it hasn't been logged what it was (Full HD. Yes, I'm an idiot). Haven't been able to repeat the error and am trying to compute the accumulated error of the NR rounds now manually. Fiddly.

We need to be able to do at most 22 rounds with `n_0 = 1000` and the individual absolute error is about `2^(-34)`. But it is not floating point, it is integer math, so what is the accumulated error at the end? Does it even accumulate?

Was the aformentioned single error just a random bitflip? An error elsewhere?

\*hng\*!

2024-03-27 08:44 UTC, sjaeckel commented
> Ah, ok, my thanks to your SO!

You're very welcome ;-)

> > I'll see what I can do by extending CI.

wow, what a ride ... In between I was not sure whether I'd simply disable the feature for MSVC ... but now it seems to work^TM ...

2024-03-27 15:30 UTC, sjaeckel commented
@jlaitine can you please check if this works for you?

2024-04-03 15:47 UTC, sjaeckel commented
> In between I was not sure whether I'd simply disable the feature for MSVC ... but now it seems to work^TM ...

aaaand in the end I disabled it for MSVC since IMO the most elegant solution is via TLS and MSVC seems to have a problem with TLS in DLLs. I'm not 100% sure what's going wrong, but since it was going fine with the static library [0] I suspect that we'd have to implement what's described in [1] and I'm simply not willing to do that, nor would I accept a PR that implements it.

If I'm mistaken there and someone with more MSVC experience wants to chime in and provide an easy fix, I'll happily accept that :)

[0] https://ci.appveyor.com/project/libtom/libtommath/builds/49507598
[1] https://learn.microsoft.com/en-us/windows/win32/dlls/using-thread-local-storage-in-a-dynamic-link-library

2024-04-03 21:01 UTC, czurnieden approved these changes
Bearhug?

2024-04-03 21:03 UTC, czurnieden commented
> https://learn.microsoft.com/en-us/windows/win32/dlls/using-thread-local-storage-in-a-dynamic-link-library

So that's the superlativ of "unnecessary complicated", isn't it?

2024-04-04 07:47 UTC, merged

2024-04-08 07:19 UTC, jlaitine commented
> @jlaitine can you please check if this works for you?

Hi sorry for the very long response time, I have been busy with some other things. I see that this already got merged, so I tested the development branch directly and this change works perfectly!

I still have a small compilation error, in PX4, which is compiled with "-Wall". Not related to this PR. I created anoter PR out of that: https://github.com/libtom/libtommath/pull/578

Thanks again,
Jukka

2024-04-08 10:20 UTC, sjaeckel commented
Thanks a lot for the feedback! Glad to hear that it works for you :)